{% set name = "supabase" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dc1001370284cbd58b99db982a405217d2e0f12f85fbc23ff743647972332a92

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >=3.7
    - pip
    - poetry
  run:
    - python >=3.7
    - postgrest >=0.10.5,<0.11.0
    - realtime >=1.0.0
    - gotrue >=1.0.0
    - httpx >=0.23.0
    - storage3 >=0.5.0
    - supafunc >=0.2.2
    - python-semantic-release

test:
  imports:
    - supabase

about:
  home: https://github.com/supabase-community/supabase-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Client for Supabase
  description: |
    Python Client for Supabase

extra:
  recipe-maintainers:
    - timkpaine
    - J0
    - anand2312
